### PR TITLE
`next-intl` localization

### PR DESCRIPTION
**Pull request by francoishernandez**
👋 @lorant-one @zsofiakm!

Here is the first draft of the `next-intl` based i18n.

For reference, it's based on one of next-intl examples ([source](https://github.com/amannn/next-intl/tree/main/examples/example-app-router-without-i18n-routing), [demo](https://next-intl-example-app-router-without-i18n-routing.vercel.app/login)).

## Some notes

- I kept the default logic of setting/getting the locale via a cookie, not sure if/how we would want to adapt this.
- The locale toggle is dynamically generated from the configured locales. This might not be ideal if the number of locales is high, but it's probably sufficient in the context of a portfolio. (Switching to a dropdown is a possibility, but I like the toggle look.
- The `mdx` content (posts/projects) now lives in localized subdirectories. In the current example I kept the same filenames across the two locales, so that switching is transparent. (If the names differ, switching locale will lead to 404. It might be adaptable, to redirect properly, but I did not dig deep in the code, and I like the simplicity of having next-intl triggering the state change.)
- I translated the projects and blog posts with ChatGPT for the sake of the example. (Using Indonesian to fit the profile!)

## Questions

My main question at this stage is: **how do we want to handle the `content.js` file?**

`next-intl` allows to grab the localized content (from `i18n/messages/{locale}.json` via the `useTranslations` hook, but that's not callable from `content.js`.

I have two solutions on the top of my head, but neither might be the best here:
1. deep restructuring of the `content.js` file, only keeping "settings"-like things there, and handle the localized content elsewhere:
  a. retrieve the various translations in the pages via scoped `t(X)` calls;
  b. define a specific `getContent((t) => {...}` function to call in the various pages, and return a relatively equivalent structure (not sure it would work properly);
2. somewhat similar to 1.b. but passing the needed content through props (not sure if more efficient)

Feedback and suggestions welcome!

### CODE REVIEW

**Comment by zsofiakm** [comment]
Hey @francoishernandez,

This looks great so far, both in terms of the functionality (localized mdx files) and the UI (language toggle).

## How do we want to handle the content.js file?
We have another alternative suggestion:
1. Restructure content.js (like you suggested) by moving the settings to config.js. This would include the person object, page and section display, and gallery images.
2. Create localized versions: content-en.js, content-id.js
3. Dynamically import the content.js based on locale. This could be done with the useEffect hook.

This approach would help retaining existing functionality and structure:
- The use of variables (e.g. "Subscribe to {person.firstName}'s Newsletter")
- The use of components (e.g. "I'm Selene, a design engineer at <InlineCode>FLY</InlineCode>")
- The nested structure of objects which makes it easy to understand (e.g. work experience)

Alternatively we could go with your 1/b suggestion. The only downside I see is that we would lose the above benefits (but maybe not?).

What do you think, which of these 2 options could work better?

**Comment by francoishernandez** [comment]
Thanks for the feedback!

I liked the 1.b. a bit better because it decorrelates the "logic" features and the localization. E.g. if you want to get your content translated, you'd just share `.json` file(s) and you're on your way.
But I'm not sure it would work properly. I can try and test it, and else we can fallback on the localized `content-{xx}.js`.


## New issue: proper handling of localized mdx content
I encountered an other issue though: the localized mdx based pages do not seem properly embedded at build time. (Though it appears to work on my local build, probably because falling back to some local paths, it fails on Vercel.)

I'm not super familiar yet with the NextJS build specifics, but maybe we could adapt the `generateStaticParams` functions to fit our needs.
Open to ideas/suggestions here as well :)

**Comment by zsofiakm** [comment]
Re: localization. Sounds good, appreciate you testing it! It's definitely true that the `.json` files are industry standard.

As for the issue you mentioned, I'll let @lorant-one take that one.

**Comment by francoishernandez** [comment]
Looks like third time's the charm. `next-intl` does not support SSG with mixed routing, so I switched to full i18n routing.
I had to refactor a few things but I think we're on a very good track here.

bd701f1 -> move most components to a specific `src/components` for clarity before creating the `[locale]` slug
ee9d20d -> setup next-intl with routing, following the [official docs](https://next-intl-docs.vercel.app/docs/getting-started/app-router/with-i18n-routing)
e5042b0 -> make the content creation dynamic from localized `{en,id}.json` messages

@lorant-one @zsofiakm let me know what you think!

**Comment by zsofiakm** [comment]
Hey @francoishernandez, 
Thanks for your work on this, after testing it, it works great.

## Merging changes
Looking at the files, i18n introduced additional complexity which might make it harder to get started if someone is only looking to create a single-language portfolio. For this reason, would you be okay with **keeping i18n on a dedicated branch, instead of merging into main**?

## i18n branch
If we keep the changes on a dedicated branch, here's what we could do to make it discoverable:
- Add information on i18n to the Magic Portfolio website
- Deploy a demo app
- Update the readme with a guide for localization

It will be a bit of extra work to keep this branch up-to-date but I think it would be manageable.

## Potential topics
The improvements you mentioned sound good and some of them are low hanging fruit. I'll add those to a GitHub project to make sure they're not forgotten, and we can tackle them separately.

Let me know if this sounds OK or if you recommend something else, and I can create the branch.

**Comment by francoishernandez** [comment]
Thanks for the feedback!

I agree about the additional complexity, but I’m not sure maintaining a separate branch would be less of a pain. (You would probably at least need to grab my first commit to align components location to retain some alignment).

I see two major pain points at this stage:
1. the ˋcontent.js` localisation which requires to align with the json files;
2. the explicit locale based routing.

The rest should mainly be transparent for an onboarding user.

Here are some suggestions to try and make it work:

For 1.
- [ ] Support a simple `content.js` file for the single locale case (not sure how it would work, but surely doable);
- [ ] Move the blog posts and work projects mdx directories up in the chain (e.g. a `content` folder at root) ;
- [ ] Add some documentation somewhere, explaining core concepts, and pointing explicitly to files/sections to modify.

For 2.
- [ ] Investigate some cleaner way to use the dedicated `next-intl` router in once-ui components;
- [ ] Clarify the single locale case to prevent showing unnecessary locale in routes.

If we check all these boxes, do you think we can make it work in a single branch ?

Maybe we could start by merging the first commit separately to get a better view of the « true » i18n related changes.

**Pull request merged**
